### ISSUE TITLE
Failed to execute sev_component_test.py with some argument. IndexError: string index out of range.

### ISSUE THREAD

**Issue by ChristinaHsu0115** [AMDEPYC/sev_component_test#9]
Failed to execute sev_component_test.py with some argument.
The python(sev_component_test.py) can NOT be executed successfully. Error message : IndexError: string index out of range.
Could you help to ask AMD how to fix it? Thank you.

Note. AMD Turin Dense CPU

Test Procedure:
1.	Enabled BIOS settings as below:
SSME: Enabled
SEV Control : Enabled
SEV-ES ASID Space Limit: 100
SEV-SNP Support : Enabled
Iommu: Enabled
2.	Boot into RHEL9.4 and install below packages
>yum install qemu-kvm libvirt* git-lfs pyrhon3-pip git
>pip3 install cpuid
>pip3 install package
3.   Download sev_componet_test file on github website.
      [GitHub - AMDEPYC/sev_component_test](https://github.com/AMDEPYC/sev_component_test)
      Unzip the file and save it.
4.	Start to run sev test with sev_componment_test.
>python3 ./sev_component_test/sev_component_test/sev_component_test.py –t sev
=> Passed.
5.  Start to run test to only check for enablement 
>python3 ./sev_component_test/sev_component_test/sev_component_test.py –e
=> Failed. The python sev_component_test can NOT be executed successfully. IndexError: string index out of range.
![STEP5-1](https://github.com/user-attachments/assets/9febbe54-2294-4632-a6c4-aa46d1542327)
![STEP5-2](https://github.com/user-attachments/assets/67d64ffa-889b-4138-bb87-2be0c1c8bb96)
6. Start to run automatic encryption test functionality.
>python3 ./sev_component_test/sev_component_test/sev_component_test.py –at
=> Failed. The python sev_component_test can NOT be executed successfully. IndexError: string index out of range.
![STEP6-1](https://github.com/user-attachments/assets/69fa29f3-ee0e-4e6a-ac7f-015a631dba39)
![STEP6-2](https://github.com/user-attachments/assets/8c2914bc-c85e-422d-ab7a-4a841fd6e46c)

**Comment by DGonzalezVillal** [comment]
Try running
"sudo modprobe msr" 
and then run it again

**Comment by DGonzalezVillal** [comment]
Hello this was part of a padding issue, if you don't have all of the MSR components enabled, the python bin function shortens the binary number, causing the index out of range issue.

I fixed it with string padding here:
7c8ff92a1759963b9374ca2abb44559cfc0cb7ad
